[package]
name = "burn-unet"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.18.0", features = ["train", "wgpu", "ndarray", "tui", "fusion", "autotune", "tch"] }
bytemuck = "1.23.1"
colorous = "1.0.16"
gdal = { version = "0.17.0", features = ["array"], optional = true }
ndarray = { version = "0.16.1", features = ["serde"] }
plotters = "0.3.7"
serde = { version = "1.0.219", features = ["alloc", "derive"] }
serial_test = "3.2.0"
walkdir = "2.5.0"


[features]
default = []
gdal = ["dep:gdal"] 
ndarray = []
torch = []
wgpu = []
mamaba = []
